name: Build and Deploy
on:
  pull_request:
    types: [labeled]
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  build:
    needs: docker-login
    strategy:
      matrix:
        service: [web, db, words]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - working-directory: ${{ matrix.service }}
      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.event.pull_request.head.sha }} -f Dockerfile .
      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.event.pull_request.head.sha }}
      - name: Notify
        run: echo "${{ matrix.service }} pushed successfully 🎉"
