name: Build and Deploy
on:
  pull_request:
    types: [labeled]
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  build:
    needs: docker-login
    strategy:
      matrix:
        service: [web, db, words]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/workflows:${{ matrix.service }}-latest 
      - name: Notify
        run: echo "${{ matrix.service }} pushed successfully"
